# Generated by Django 4.1.5 on 2023-01-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['price'], name='bookapi_boo_price_2d39da_idx'),
        ),
    ]
