# Generated by Django 4.1.5 on 2023-01-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0002_book_bookapi_boo_price_2d39da_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
