# Generated by Django 4.1.5 on 2023-01-06 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0003_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapi.book')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_name', to='bookapi.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_book', to='bookapi.book')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='author_books', through='bookapi.AuthorBook', to='bookapi.book'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['book'], name='bookapi_rev_book_id_ce7203_idx'),
        ),
        migrations.AddIndex(
            model_name='authorbook',
            index=models.Index(fields=['author'], name='bookapi_aut_author__bb6f38_idx'),
        ),
        migrations.AddIndex(
            model_name='authorbook',
            index=models.Index(fields=['book'], name='bookapi_aut_book_id_b4692a_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='bookapi_aut_name_663a36_idx'),
        ),
    ]
