# Generated by Django 4.1.5 on 2023-01-06 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0004_author_review_authorbook_author_books_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='author',
            new_name='bookapi_aut_name_id_87f888_idx',
            old_name='bookapi_aut_name_663a36_idx',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_name', to='bookapi.book'),
        ),
    ]
