# Generated by Django 4.1.5 on 2023-01-06 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0005_rename_bookapi_aut_name_663a36_idx_bookapi_aut_name_id_87f888_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='author',
            new_name='bookapi_aut_name_663a36_idx',
            old_name='bookapi_aut_name_id_87f888_idx',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='bookapi.author'),
        ),
    ]
