# Generated by Django 4.1.5 on 2023-01-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0006_rename_bookapi_aut_name_id_87f888_idx_bookapi_aut_name_663a36_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorbook',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authorbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='AuthorBook',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
