# Generated by Django 4.1.5 on 2023-01-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0007_remove_authorbook_author_remove_authorbook_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('reviewer', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='bookapi_boo_price_2d39da_idx',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='No genre specified', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='No ISBN specified', max_length=13),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='purchase_history',
            field=models.ManyToManyField(to='bookapi.book'),
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapi.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapi.author'),
        ),
    ]
